export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_FAILURE = 'AJAX_CALL_FAILURE';

// plop added
export const GET_ALL_TESTBELTS_SUCCESS = 'GET_ALL_TESTBELTS_SUCCESS';
export const GET_TESTBELT_SUCCESS = 'GET_TESTBELT_SUCCESS';
export const DELETE_TESTBELT_SUCCESS = 'DELETE_TESTBELT_SUCCESS';
export const SAVE_TESTBELT_SUCCESS = 'SAVE_TESTBELT_SUCCESS';

// plop added
export const GET_ALL_TOPTOPS_SUCCESS = 'GET_ALL_TOPTOPS_SUCCESS';
export const GET_TOPTOP_SUCCESS = 'GET_TOPTOP_SUCCESS';
export const DELETE_TOPTOP_SUCCESS = 'DELETE_TOPTOP_SUCCESS';
export const SAVE_TOPTOP_SUCCESS = 'SAVE_TOPTOP_SUCCESS';

// plop added
export const GET_ALL_AGORA_VAIS_SUCCESS = 'GET_ALL_AGORA_VAIS_SUCCESS';
export const GET_AGORA_VAI_SUCCESS = 'GET_AGORA_VAI_SUCCESS';
export const DELETE_AGORA_VAI_SUCCESS = 'DELETE_AGORA_VAI_SUCCESS';
export const SAVE_AGORA_VAI_SUCCESS = 'SAVE_AGORA_VAI_SUCCESS';

//-- APPEND ITEMS HERE --



